### ISSUE TITLE
ephys-3 copying seems super slow. 

### ISSUE THREAD

**Issue by takacsflora** [cortex-lab/PinkRigs#42]

**Comment by cbimbo** [comment]
Seems like it's also happening in ephys-4 (not always).

**Comment by cbimbo** [comment]
This is due to getting the MD5 hash for the file on the server. For some reason, it's taking forewer (>60 times slower than when run locally). Three solutions I can think of:
- removing that check
- running it at the very end, once everything has been copied
- recopying it locally, and computing the md5 hash locally

**Comment by cbimbo** [comment]
I removed the MD5 hash.
